###UI setup
library(shiny)
library(shinyjs)
library(mlbench)
library(plotly)
library(shinythemes)
library(dplyr)
library(shinyFiles)
library(digest)
library(gridExtra)
source("tab_setup.R")
source("tab_process.R")
source("tab_analyze.R")
source("shinyjs_tab.R")